add_subdirectory(conjugateGradientCudaGraphs)
add_subdirectory(conjugateGradientMultiBlockCG)
add_subdirectory(conjugateGradientMultiDeviceCG)
add_subdirectory(cubDeviceFind)
add_subdirectory(cubDeviceSegmentedScan)
add_subdirectory(cubDeviceTransform)
add_subdirectory(cudaNvSci)
add_subdirectory(jitLto)
add_subdirectory(libcuxxMdspan)
add_subdirectory(libcuxxRandom)
add_subdirectory(lineOfSight)
add_subdirectory(oceanFFT)
add_subdirectory(randomFog)
